complited reader_writer
Sage-Cat/SageParser pull request #3
Opened 2023-12-12 21:51 UTC by DanyloPlotskykh

please review

2023-12-13 02:10 UTC, Sage-Cat requested changes

2023-12-13 02:10 UTC, Sage-Cat commented on lib/CMakeLists.txt
> +target_link_libraries(SageDocsLib PRIVATE rapidcsv::rapidcsv pugixml::pugixml xlnt::xlnt)
Why was icu::icu removed?

2023-12-13 02:10 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +    std::shared_ptr<Dataset> XmlReader::readData()
use code formatter, like Prettier Code Formatter to avoid such missing of spaces between funcs and many other

2023-12-13 02:10 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +        // std::wcout.imbue(std::locale(std::locale(), new std::codecvt_utf8<wchar_t, 0x10FFFF, std::generate_header>()));
redudant?
remove if is not needed

2023-12-13 02:10 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +        pugi::xml_node items = doc.child("Root");
What is "Root"?
Avoid having such weird dependencies on names.
You don't parse it by keys defined in example files. Keys could be any, like "Root" or "Column" or "Row"
Your task is actually to take 2 deepest layers of XML tree structure not depending on their's names

2023-12-13 02:10 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +        // Сохраняем XML-документ в файл
avoidn using not english comments

2023-12-13 02:10 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +TEST(SageDocsLibTest, MinimalXmlWorkCycle)
Did you really tested this?

2023-12-13 02:10 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +    reader->setFilePath("C:\\project\\example.xml ");
Push this file to the repository and make tests to work with it like I did for case with CSV

2023-12-13 02:29 UTC, Sage-Cat requested changes

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +            throw std::invalid_argument("File path does not exist.");
consider providing the file path in the message for easier debugging.

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +        for (auto parent = items; parent != PUGIXML_NULL; parent = parent.next_sibling())
Performance of this part is really bad.
The nested loops and parent traversal in readData seem a bit complex. It might be beneficial to refactor this part for clarity and maintainability.

Use chatgpt

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +                dataset->dataRows.push_back(tmp);
The way you extract data into Dataset is logical. However, ensure that the structure of the XML aligns with this logic.

I mean that even if we are expecting xml file to be formated tabled way, we still need to make some base "if else" for corner cases. Consider them.

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +            return dataset;
`return` inside loop? Are you mad or smth? What's the point of this?
You might want to double-check if this is the intended behavior. I expect it to be wrong

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +            throw std::invalid_argument("Directory path does not exist.");
similar to reader
give a path of file to msg

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +        // queue for columnNames
The use of a queue for columnNames is interesting but might not be necessary. Provide, please, some comments about this matter. Why did you make this?

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +        declaration.append_attribute("encoding") = "WINDOWS-1251";
The encoding is set to WINDOWS-1251. Ensure this is compatible with the use case.
Better change it to UTF-8, cos we expect it to be default encoding.

Consider adding some `setEncoding` method to IReader and IWriter, similar to `setFilePath`

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +        doc.save_file("result.xml")
`doc.save_file("result.xml")` saves to a fixed filename. Consider using `m_filePath` to make it dynamic.

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Writers/XmlWriter.cpp
> +                auto node_name = q.front();
Be cautious with `q.front()` and `q.pop()`. Ensure the queue is not empty to avoid runtime errors.

2023-12-13 02:29 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +    reader->setFilePath("C:\\project\\example.xml ");
The path in `reader->setFilePath` has a trailing space. Ensure paths are sanitized.

2023-12-13 02:29 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +    auto writer = SageDocs::WriterFactory::createWriter(SageDocs::WriterFileType::CSV);
The writer is set to CSV, but the file path suggests XML (output_testMinimalXMLWorkCycle.xml). Double-check the file format consistency.

2023-12-13 02:29 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +            while (parent.first_child())
Adding comments explaining complex parts, especially in this `readData`, would be helpful.

2023-12-13 02:40 UTC, Sage-Cat reviewed
Also you need to integrate your new classes into `ReaderFactory` and `WriterFactory`

2023-12-18 18:02 UTC, DanyloPlotskykh commented on lib/CMakeLists.txt
> +target_link_libraries(SageDocsLib PRIVATE rapidcsv::rapidcsv pugixml::pugixml xlnt::xlnt)
done

2023-12-18 18:02 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +    std::shared_ptr<Dataset> XmlReader::readData()
done

2023-12-18 18:02 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +        // std::wcout.imbue(std::locale(std::locale(), new std::codecvt_utf8<wchar_t, 0x10FFFF, std::generate_header>()));
done

2023-12-18 18:02 UTC, DanyloPlotskykh commented on lib/Writers/XmlWriter.cpp
> +        // Сохраняем XML-документ в файл
done

2023-12-18 18:03 UTC, DanyloPlotskykh commented on tests/testSageDocsLib.cpp
> +    reader->setFilePath("C:\\project\\example.xml ");
done

2023-12-18 18:03 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +            return dataset;
done

2023-12-18 18:04 UTC, DanyloPlotskykh commented on tests/testSageDocsLib.cpp
> +    auto writer = SageDocs::WriterFactory::createWriter(SageDocs::WriterFileType::CSV);
done

2023-12-23 17:27 UTC, Sage-Cat requested changes

2023-12-23 17:27 UTC, Sage-Cat commented on lib/CMakeLists.txt
> +target_link_libraries(SageDocsLib PRIVATE rapidcsv::rapidcsv icu::icu pugixml::pugixml xlnt::xlnt)
Шо за треш?
Нашо ти ще декілька рядків понавставляв?

2023-12-23 17:27 UTC, Sage-Cat commented on lib/Readers/XmlReader.cpp
> +            throw std::invalid_argument("File path does not exist.");
@DanyloPlotskykh шо з цим?

2023-12-23 17:27 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +    reader->setFilePath("C:\\project\\example.xml ");
@DanyloPlotskykh це не пофіксив

2024-01-13 23:08 UTC, DanyloPlotskykh commented
rewrite writer, fixed bugs. Time complexity - O(n). Added new exeptions.

2024-01-14 11:26 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +            throw std::invalid_argument("File path does not exist.");
done

2024-01-14 11:26 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +        for (auto parent = items; parent != PUGIXML_NULL; parent = parent.next_sibling())
done

2024-01-14 11:26 UTC, DanyloPlotskykh commented on lib/Writers/XmlWriter.cpp
> +            throw std::invalid_argument("Directory path does not exist.");
done

2024-01-14 11:27 UTC, DanyloPlotskykh commented on lib/Readers/XmlReader.cpp
> +            while (parent.first_child())
done

2024-01-14 11:28 UTC, DanyloPlotskykh commented on lib/CMakeLists.txt
> +target_link_libraries(SageDocsLib PRIVATE rapidcsv::rapidcsv icu::icu pugixml::pugixml xlnt::xlnt)
done

2024-01-15 12:45 UTC, Sage-Cat commented on tests/testSageDocsLib.cpp
> +TEST(SageDocsLibTest, MinimalXmlWorkCycle)
@DanyloPlotskykh did you run tests?

2024-02-28 16:57 UTC, closed without merging